<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
        <PackageReference Include="xunit.v3" Version="4.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Fini.v3\Fini.v3.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Library.fs" />
    </ItemGroup>

</Project>